### ISSUE TITLE
Particle.io WEB IDE: compile error for core @1.4.4

### ISSUE THREAD

**Issue by nebucaz** [hirotakaster/MQTT#88]
When including MQTT.h and compile, errors were thrown:

`lib/MQTT/MQTT.h:157:0: undefined reference to "os_mutex_lock"`
`lib/MQTT/MQTT.h:158:0: undefined reference to "os_mutex_unlock"`

Hardware: Spark Core
DeviceOS: 1.4.4 (default)

Successfully compiles for Photon (@2.0.1) on local Particle Workbench and Web-IDE. 
Any idea, how to make this work on core (@1.4.4)?

**Comment by hirotakaster** [comment]
@nebucaz now update to 0.3.31. please use this version.

**Comment by nebucaz** [comment]
Ccompiles now, thanks. 
Also found out, that the library MQTT_a0e4 works too.
